config/routes.rb
Rails.application.routes.draw do
  root to: 'issues#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/signup', to: 'users#new'
  post '/users', to: 'users#create'

  
  resources :issues
  resources :pros, only: [:new, :create, :destroy]
  resources :cons, only: [:new, :create, :destroy]
  resources :users, only: [:index, :new, :create, :edit, :update, :destroy, :show]

  get '/users/:id/delete', to: 'users#confirmdestroy', as: 'confirmdestroy_user'
end

app/models/con.rb
class Con < ActiveRecord::Base
  belongs_to :issue
  validates :weight, presence: true
  validates :name, presence: true
end

app/models/issue.rb
class Issue < ActiveRecord::Base
  belongs_to :user
  delegate :name, to: :user, prefix: true
  has_many :pros
  has_many :cons
  validates :name, presence: true

  def self.open_issues
    open_issues = Issue.where("open = ?", true)
  end

  def self.public_issues
    public_issues = Issue.where("private = ?", false)
  end

  def self.private_issues
    private_issues = Issue.where("private = ?", true)
  end

  def average_pros
    @weight = []
    self.pros.each do |pro|
      @weight << pro.weight
    end
    average
  end

  def average_cons
    @weight = []
    self.cons.each do |con|
      @weight << con.weight
    end
    average
  end

  def average
    if @weight.size > 0
      @weight.inject(0.0) {|sum, el| sum + el}
    else
      0
    end
  end

end

app/models/pro.rb
class Pro < ActiveRecord::Base
  belongs_to :issue
  validates :weight, presence: true
  validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :issues
  has_secure_password
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, length: {minimum: 6}, on: :create
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end

end

app/controllers/cons_controller.rb
class ConsController < ApplicationController
  before_action :select_con, only: [:destroy]
  before_filter :authorize

  def new
    @con = Con.new
  end

  def create
    @con = Con.create(con_params)
    respond_to do |format|
      format.js
    end
  end

  def destroy
    @con.destroy
    respond_to do |format|
      format.js
    end
  end

  private

  def con_params
    params.require(:con).permit(:name, :weight, :issue_id)
  end

  def select_con
    @con = Con.find(params[:id])
  end

end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :select_issue, only: [:show, :edit, :update, :destroy]
  before_filter :authorize

  def index
    @issues = Issue.open_issues && Issue.public_issues
  end

  def new
    @issue = Issue.new
  end

  def create
    @issue = Issue.new(issue_params)
    @issue.user_id = current_user.id
    @issue.save
    if @issue.save
      redirect_to issue_path(@issue)
    else
      render new_issue_path
    end
  end

  def update
    @issue.update(issue_params)
    @issue.save
    redirect_to issue_path(@issue)
  end

  def show
    @pro = Pro.new
    @con = Con.new
  end

  def destroy
    @issue.destroy
    redirect_to issues_path
  end

  private

  def issue_params
    params.require(:issue).permit(:name, :open, :private)
  end

  def select_issue
    @issue = Issue.find(params[:id])
  end

end

app/controllers/pros_controller.rb
class ProsController < ApplicationController
  before_action :select_pro, only: [:destroy]
  before_filter :authorize

  def new
    @pro = Pro.new
  end

  def create
    @pro = Pro.create(pro_params)
    respond_to do |format|
      format.js
    end
  end

  def destroy
    @pro.destroy
    respond_to do |format|
      format.js
    end
  end

  private

  def pro_params
    params.require(:pro).permit(:name, :weight, :issue_id)
  end

  def select_pro
    @pro = Pro.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.create(uid: request.env['omniauth.auth']['uid'], provider: request.env['omniauth.auth']['provider'], name: request.env['omniauth.auth']['info']['name'])

    session[:user_id] = @user.id
    render 'issues/index'
    # user = User.find_by_email(params[:email])
    # if user && user.authenticate(params[:password])
    #   session[:user_id] = user.id
    #   redirect_to '/'
    # else
    #   redirect_to '/login'
    # end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :select_user, only: [:show, :update, :edit, :destroy]
  skip_before_action :require_login, only: [:new, :create]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render new_user_path
    end
  end

  def edit
    # @user = User.find(user_params)
    @user = User.find(params[:id])
    # binding.pry
  end

  def update
    @user.update(user_params)
    @user.save
    redirect_to user_path(@user)
  end

  def confirmdestroy

  end

  def destroy
    current_user.delete
    session[:user_id] = nil
    redirect_to '/login'
  end

  def show
    @public_issues = @user.issues.public_issues
    @private_issues = @user.issues.private_issues
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def select_user
    @user = User.find(params[:id])
  end

end

app/views/cons/_con.html.erb
<li data-id="<%= con.id %>">con: <%= con.name %>  --  weight: <%= con.weight %> <a href="/cons/<%= con.id %>/" data-remote="true" data-method="delete" class="delete_button" >X</a></li>

app/views/cons/_new_con.html.erb
<%= form_for(@con, remote: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :weight %>
  <%= f.text_field :weight %>
  <%= f.hidden_field :issue_id, value: @issue.id %>
  <%= f.submit %>
<% end %>

app/views/cons/create.js.erb
$('ul.con').append('<%= j render partial: "con", locals: {con: @con} %>')
$('.recommendations').html('<h2><strong><%= IssuesDecorator.new(@con.issue).recommendation(@con.issue) %></strong></h2>')

app/views/cons/destroy.js.erb
$('[data-id=<%=@con.id%>]').hide()
$('.recommendations').html('<h2><strong><%= IssuesDecorator.new(@con.issue).recommendation(@con.issue) %></strong></h2>')

app/views/issues/_new_form.html.erb
<%= form_for issue do |f| %>
  <% if issue.errors.any? %>
    <div id="error_explanation">
      <h2>
        The following errors prevented this issue from saving:
      </h2>
      <ul>
      <% issue.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :name, "Issue Name" %> <br>
  <%= f.text_field :name %> <br><br>

  <%= f.label :private, "Make issue private? :"  %>
  <%= f.check_box :private %> <br> <br>

  <button class="btn btn-default"><%= f.submit %></button>

<% end %>

app/views/issues/edit.html.erb
<h3>Edit Issue</h3>
<%= render 'new_form', issue: @issue %>

app/views/issues/index.html.erb
<h1>Open Public Issues</h1>
<% @issues.each do |issue| %>
  <%= link_to issue.name, issue_path(issue) %> <br>
<% end %>
<br>

<button class="btn btn-default">
<%= link_to "New Issue", new_issue_path %>
</button>

app/views/issues/new.html.erb
<h3>Create a new Issue</h3>
<%= render 'new_form', issue: @issue %>

app/views/issues/show.html.erb
<h3> <%= @issue.name %> </h3>
<h2>Issue Owner: <%= @issue.user_name %></h2> <br>

<div class="recommendations">
  <h2><strong><%= IssuesDecorator.new(@issue).recommendation(@issue) %></strong></h2>
</div>

<div class="container-fluid container-custom">
  <div class="col-sm-6">
    <div class="accordion">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h2 class="panel-title">Pros of Doing This</h2>
        </div>
        <div class="panel-collapse collapse in" aria-expanded="true">
          <div class"panel-body">
            <ul class="pro">
              <% @issue.pros.each do |pro| %>
              <%= render partial: 'pros/pro', locals: {pro: pro} %>
            <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="col-sm-6">
    <div class="accordion">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h2 class="panel-title">Cons of Doing This</h2>
        </div>
        <div class="panel-collapse collapse in" aria-expanded="true">
          <div class"panel-body">
            <ul class="con">
              <% @issue.cons.each do |con| %>
              <%= render partial: 'cons/con', locals: {con: con} %>
            <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<br>
<br>
<br>
<br>
<div class="container-fluid container-custom">
  <% if current_user == @issue.user %>
    <h4>Add a new Pro</h4> <br>
    <%= render 'pros/new_pro' %> <br> <br>

    <h4>Add a new Con</h4> <br>
    <%= render 'cons/new_con' %> <br> <br>

    <button class="btn btn-default"><%= link_to "Edit Issue", edit_issue_path %></button>
    <button class="btn btn-default"><%= link_to "Delete Issue", issue_path, method: :delete %></button>
  <% end %>
  <br>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flipside</title>
  <%= favicon_link_tag 'assets/images/favicon.png' %>


  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Roboto+Condensed:400,300,400italic,700" %>
  <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Open+Sans:400,400italic,700" %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


  	<!-- SIDEBAR -->
  	<div class="sidebar">

  		<nav class="navbar navbar-custom font-alt">
  			<div class="navbar-header">
  				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#custom-collapse">
  					<span class="sr-only">Toggle navigation</span>
  					<span class="icon-bar"></span>
  					<span class="icon-bar"></span>
  					<span class="icon-bar"></span>
  				</button>

  				<!-- YOU LOGO HERE -->
  				<a class="navbar-brand" href="/">
  					<!-- IMAGE OR SIMPLE TEXT -->
            FLIP/ƧIDE
  				</a>
  			</div>

  			<div class="collapse navbar-collapse" id="custom-collapse">

  				<ul class="nav navbar-nav">
            <% if current_user %>
              <li><%= current_user.name %><li>
              <li><%= link_to "My Profile", user_path(current_user) %></li>
              <li><%= link_to "Issues", issues_path %></li>
              <li><%= link_to "Users", users_path %></li>
              <li><%= link_to "Log Out", '/logout' %> </li>
            <% else %>
              <li><%= link_to 'Log In', '/login' %></li>
              <li><%= link_to 'Sign Up', '/signup' %></li>
            <% end %>
  				</ul>
  			</div>

  		</nav>


  	</div>
  	<!-- /SIDEBAR -->
    <div class="wrapper">
      <div class="main-view-page">
          <%= yield %>
      </div>
    </div>
</body>
</html>

app/views/pros/_new_pro.html.erb
<%= form_for(@pro, remote: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :weight %>
  <%= f.text_field :weight %>
  <%= f.hidden_field :issue_id, value: @issue.id %>
  <%= f.submit %>
<% end %>

app/views/pros/_pro.html.erb
<li data-id="<%= pro.id %>">pro: <%= pro.name %>  --  weight: <%= pro.weight %> <a href="/pros/<%= pro.id %>/" data-remote="true" data-method="delete" class="delete_button" >X</a></li>

app/views/pros/create.js.erb
$('ul.pro').append('<%= j render partial: "pro", locals: {pro: @pro} %>')
$('.recommendations').html('<h2><strong><%= IssuesDecorator.new(@pro.issue).recommendation(@pro.issue) %></strong></h2>')

app/views/pros/destroy.js.erb
$('[data-id=<%=@pro.id%>]').hide()
$('.recommendations').html('<h2><strong><%= IssuesDecorator.new(@pro.issue).recommendation(@pro.issue) %></strong></h2>')

app/views/users/_confirmdestroy_form.html.erb
<%= form_for :user, method: :delete, url: user_path(current_user) do |f| %>
  <h3><%= current_user.name %></h3><br>
  <%= f.submit("Confirm Delete?", class: 'btn btn-danger btn-circle btn-lg') %> <br>
<% end %>

app/views/users/_edit_form.html.erb
<%= form_for :user, method: :patch, url: user_path(user) do |f| %>
  Name: <br> <%= f.text_field :name %> <br> <br>
  Email: <br> <%= f.text_field :email %> <br> <br>
  Password: <br> <%= f.password_field :password %> <br> <br>
  Password Confirmation: <br> <%= f.password_field :password_confirmation %> <br> <br>
  <%= f.submit("Update!", class: 'btn btn-dark btn-circle btn-lg') %> <br>
<% end %>

app/views/users/_new_edit_form.html.erb
<%= form_for :user, url: '/users' do |f| %>
  Name: <br> <%= f.text_field :name %> <br> <br>
  Email: <br> <%= f.text_field :email %> <br> <br>
  Password: <br> <%= f.password_field :password %> <br> <br>
  Password Confirmation: <br> <%= f.password_field :password_confirmation %> <br> <br>
  <%= f.submit %> <br>
<% end %>

app/views/users/_new_form.html.erb
<%= form_for user, url: users_path do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2>
        The following errors prevented this user from saving:
      </h2>
      <ul>
      <% user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  Name: <br> <%= f.text_field :name %> <br> <br>
  Email: <br> <%= f.text_field :email %> <br> <br>
  Password <em>(minimum 6 char)</em>: <br> <%= f.password_field :password %> <br> <br>
  Password Confirmation: <br> <%= f.password_field :password_confirmation %> <br> <br>
  <%= f.submit("Create!", class: 'btn btn-dark btn-circle btn-lg') %> <br>
<% end %>

app/views/users/confirmdestroy.html.erb
<%= render 'confirmdestroy_form', user: @user %>

app/views/users/edit.html.erb
<h3>Edit User</h3>
<%= render 'edit_form', user: @user %>

<br> <br>

<b>
<%= link_to "Delete User", confirmdestroy_user_path %>
</b>

app/views/users/index.html.erb
<h1>All Users</h1>

<% @users.each do |user| %>
  <%= link_to user.name, user_path(user) %><br>
<% end %>

app/views/users/new.html.erb
<h3>Create a New User</h3>
<%= render 'new_form', user: @user %>

app/views/users/show.html.erb
<h3><%= @user.name %></h3>
<br>
<h2>Public Issues</h2>
  <% @public_issues.each do |issue| %>
    <%= link_to issue.name, issue_path(issue) %><br>
<% end %>


<br> <br>
<% if current_user == @user%>
<h2>Private Issues</h2>
  <% @private_issues.each do |issue| %>
    <%= link_to issue.name, issue_path(issue) %> <br>
  <% end %>
  <br> <br>
  <%= link_to "Edit User", edit_user_path %>
<% end %>
</b>